//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestoOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passport
    {
        public int ID_Passport { get; set; }
        public string Seria { get; set; }
        public string Number { get; set; }
        public int ID_Client { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
