//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestoOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchasedService
    {
        public Nullable<int> ID_Zayavka { get; set; }
        public Nullable<int> ID_Services { get; set; }
        public int ID_PurchasedService { get; set; }
    
        public virtual Servicess Servicess { get; set; }
        public virtual Zayavka Zayavka { get; set; }
    }
}
