//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestoOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zayavka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zayavka()
        {
            this.PurchasedService = new HashSet<PurchasedService>();
        }
    
        public int ID_Zayavka { get; set; }
        public int ID_Client { get; set; }
        public Nullable<int> ID_TypeDiet { get; set; }
        public int ID_Room { get; set; }
        public double FinalPrice { get; set; }
        public System.DateTime DataZaezd { get; set; }
        public System.DateTime DataViezd { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Room Room { get; set; }
        public virtual TypeDiet TypeDiet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchasedService> PurchasedService { get; set; }
    }
}
